# Generated by Django 3.2.10 on 2023-09-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
